apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: zonhor-test
  # 部署名字
  name: zonhor-test
spec:
  replicas: 3
  # 用来查找关联的 Pod，所有标签都匹配才行
  selector:
    matchLabels:
      app: zonhor-test
  # 定义 Pod 相关数据
  template:
    metadata:
      labels:
        app: zonhor-test
    spec:
      # 定义容器，可以多个
      containers:
        - name: test-k8s # 容器名字
          image: ccr.ccs.tencentyun.com/zonhor/test:1.0.1 # 镜像
