apiVersion: v1
kind: Service
metadata:
  name: zonhor-test
spec:
  selector:
    app: zonhor-test
  # 默认 ClusterIP 集群内可访问，NodePort 节点可访问，LoadBalancer 负载均衡模式（需要负载均衡器才可用）
  type: NodePort
  ports:
    - port: 9059        # 本 Service 的端口
      targetPort: 9059  # 容器端口
      nodePort: 31000   # 节点端口，范围固定 30000 ~ 32767
